#!/usr/bin/env bash

# Canonical WACV Phase 1 Core-6 task configuration. Historical probes live in
# legacy/cleanup_20260603 or the full legacy runner snapshot.

task_config() {
  local task_id="$1"
  TASK_NAME=""
  TASK_KIND=""
  IMAGE=""
  SOURCE_PROMPT=""
  TARGET_PROMPT=""
  ATTENTION_TARGET_WORDS=""
  CHANGED_TARGET_WORDS=""
  SUPPORT_EDIT_OPERATION="auto"
  SUPPORT_NEW_TOKENS=""
  SUPPORT_HOST_TOKENS=""
  SUPPORT_REMOVED_TOKENS=""
  SUPPORT_LOCAL_TARGET_PROMPT=""
  SUPPORT_V2_CANDIDATE=""
  SUPPORT_V3_CANDIDATE="operation_default"
  SUPPORT_V3_RELATION="auto"
  SEMANTIC_PHRASE=""
  SEMANTIC_DILATE="0"
  SEMANTIC_BLUR="0"
  SUPPORT_RELATION="auto"
  SUPPORT_SEMANTIC_RELATION=""
  SUPPORT_SEMANTIC_EXPAND_X=""
  SUPPORT_SEMANTIC_EXPAND_Y=""
  SUPPORT_SEMANTIC_BAND_RATIO=""
  SUPPORT_SEMANTIC_OVERLAP_RATIO=""
  SUPPORT_SEMANTIC_THRESHOLD=""
  SUPPORT_PRESET=""
  TASK_EDIT_STRENGTH_MULTIPLIER=""
  TASK_DECAL_REF_GUIDANCE_SCALE=""
  TASK_DECAL_REF_LUMA_PRESERVE=""
  TASK_DECAL_REF_GRADIENT_PRESERVE=""
  TASK_DECAL_REF_SMOOTH_KERNEL=""
  TASK_COMPLETION_CLEAN_DELTA_SCALE=""
  TASK_COMPLETION_CLEAN_DELTA_SCHEDULE_START=""
  TASK_COMPLETION_CLEAN_DELTA_SCHEDULE_STOP=""
  TASK_COMPLETION_CLEAN_DELTA_SCHEDULE_POWER=""
  TASK_OPFIELD_DECAL_HEDIT=""
  TASK_OPFIELD_DECAL_TEXT=""
  TASK_OPFIELD_DECAL_REC=""
  TASK_OPFIELD_DECAL_TRAJ=""
  DECAL_SHAPE=""
  DECAL_COLOR=""
  DECAL_BOX=""
  DECAL_SLANT_X="0.0"
  DECAL_PERSPECTIVE_Y="0.0"
  DECAL_EDGE_FEATHER_RADIUS="0.0"
  DECAL_TOP_FEATHER_FRAC="0.0"
  DECAL_TOP_FEATHER_MIN_ALPHA="0.0"
  DECAL_OPACITY=""
  RECOLOR_TARGET_COLOR=""
  RECOLOR_SURFACE_NAME=""
  RECOLOR_BOX=""
  RECOLOR_SOURCE_COLOR=""
  RECOLOR_FILL_HOLES="1"
  REPLACEMENT_COLOR="blue"
  REPLACEMENT_SHAPE="semantic"
  REPLACEMENT_OPACITY="0.98"
  REPLACEMENT_SCALE="0.78"
  REPLACEMENT_BLUR="0.7"
  REPLACEMENT_BACKGROUND_MODE="patch"
  REPLACEMENT_OUTLINE="0"
  REPLACEMENT_HEDIT_GUIDANCE_SCALE="0.62"
  REPLACEMENT_TEXT_GUIDANCE_SCALE="0.06"
  REPLACEMENT_REF_GUIDANCE_SCALE="0.42"
  REPLACEMENT_REC_GUIDANCE_SCALE="0.20"
  REPLACEMENT_TRAJECTORY_PRESERVE_SCALE="0.14"
  REPLACEMENT_OLD_PHRASE=""
  REPLACEMENT_TARGET_PHRASE=""

  case "${task_id}" in
    P1|cat_crown)
      TASK_NAME="cat_crown"
      TASK_KIND="accessory_semantic"
      IMAGE="${ROOT}/data/paper_images/cat_sitting_in_grass.jpg"
      SOURCE_PROMPT="A photo of a cat sitting in grass."
      TARGET_PROMPT="A photo of the same cat sitting in the same grass, wearing a small golden crown centered on top of its head between the ears."
      ATTENTION_TARGET_WORDS="crown,head"
      CHANGED_TARGET_WORDS="crown"
      SUPPORT_EDIT_OPERATION="add_object"
      SUPPORT_NEW_TOKENS="crown"
      SUPPORT_HOST_TOKENS="cat,head"
      SUPPORT_V2_CANDIDATE="new_plus_host_x_clean"
      SUPPORT_V3_RELATION="above_host"
      SEMANTIC_PHRASE="cat"
      SUPPORT_LOCAL_TARGET_PROMPT="A close-up photo of a small golden crown centered on top of a cat's head between the ears."
      ;;
    bowl_apple_inside)
      TASK_NAME="bowl_apple_inside"
      TASK_KIND="object_in_container"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_empty_ceramic_bowl_phase1.jpg"
      SOURCE_PROMPT="A top-down photo of an empty blue ceramic bowl on a wooden board in a tidy table setting, with no fruit inside the bowl."
      TARGET_PROMPT="A top-down photo of the same blue ceramic bowl on the same wooden board, with one small red apple centered inside the bowl, while the bowl, board, tableware, leaves, and background remain unchanged."
      ATTENTION_TARGET_WORDS="apple,bowl,inside"
      CHANGED_TARGET_WORDS="apple"
      SUPPORT_EDIT_OPERATION="add_object"
      SUPPORT_NEW_TOKENS="apple"
      SUPPORT_HOST_TOKENS="bowl,ceramic bowl"
      SUPPORT_V2_CANDIDATE="new_plus_host_x_clean"
      SUPPORT_V3_RELATION="inside_container"
      SEMANTIC_PHRASE="blue ceramic bowl"
      SUPPORT_RELATION="inside"
      SUPPORT_LOCAL_TARGET_PROMPT="A close-up top-down photo of one small red apple centered inside the empty blue ceramic bowl, fully within the inner basin and away from the rim."
      ;;
    P5|tshirt_star)
      TASK_NAME="tshirt_star"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_person_white_tshirt_blue_jeans_8217483.jpg"
      SOURCE_PROMPT="A close-up fashion photo of a person wearing a plain white t-shirt and blue jeans, with natural fabric folds and soft studio lighting."
      TARGET_PROMPT="The same person wearing the same white t-shirt and blue jeans, with a clearly visible medium-sized bright red star printed on the center chest, while preserving the fabric folds, shadows, jeans, pose, and background."
      ATTENTION_TARGET_WORDS="star,t-shirt,chest"
      CHANGED_TARGET_WORDS="star"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="clothing_decal"
      SUPPORT_NEW_TOKENS="star"
      SUPPORT_HOST_TOKENS="t-shirt,shirt"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="t-shirt"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="star"
      DECAL_COLOR="red"
      DECAL_BOX="0.40,0.30,0.62,0.55"
      ;;
    P4|red_chair_blue|red_chair_to_blue_chair)
      TASK_NAME="red_chair_blue"
      TASK_KIND="recolor_semantic"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_red_armchair_room_6758347.jpg"
      SOURCE_PROMPT="A photo of a red armless rounded upholstered chair in a stylish room."
      TARGET_PROMPT="A photo of the same armless rounded upholstered chair in the same stylish room, with only the fabric color changed to deep blue, no armrests added."
      ATTENTION_TARGET_WORDS="chair,blue"
      CHANGED_TARGET_WORDS="chair"
      SUPPORT_EDIT_OPERATION="recolor"
      SUPPORT_NEW_TOKENS="blue"
      SUPPORT_HOST_TOKENS="chair"
      SUPPORT_REMOVED_TOKENS="chair"
      SUPPORT_V3_RELATION="inside"
      SEMANTIC_PHRASE="chair"
      SUPPORT_RELATION="inside"
      RECOLOR_TARGET_COLOR="blue"
      RECOLOR_SURFACE_NAME="chair"
      ;;
    pillow_vertical_fabric_strip)
      TASK_NAME="pillow_vertical_fabric_strip"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_plain_pillow_sofa_phase1.jpg"
      SOURCE_PROMPT="A cozy living room photo with a plain grey pillow on a sofa, soft natural light, and a simple home interior."
      TARGET_PROMPT="A photo of the same plain grey pillow with one vertical glossy blue silk strip sewn down the center of the pillow surface, tucked naturally into the top pillow seam with soft satin highlights and smooth silk texture, while the pillow shape, sofa, table, wall, and background remain unchanged."
      ATTENTION_TARGET_WORDS="blue,silk,vertical,strip,pillow"
      CHANGED_TARGET_WORDS="blue,silk,strip"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="surface_strip"
      SUPPORT_NEW_TOKENS="blue,silk,strip"
      SUPPORT_HOST_TOKENS="pillow"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="grey pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="slanted_rectangle"
      DECAL_COLOR="58,132,215"
      DECAL_BOX="0.565,0.445,0.665,0.688"
      DECAL_SLANT_X="-0.08"
      DECAL_PERSPECTIVE_Y="0.055"
      DECAL_EDGE_FEATHER_RADIUS="7.0"
      DECAL_TOP_FEATHER_FRAC="0.16"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.0"
      DECAL_OPACITY="0.80"
      ;;
    pillow_same_color_corduroy_panel)
      TASK_NAME="pillow_same_color_corduroy_panel"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/phase2_candidates/pexels_white_pillow_brown_sofa_6312089.jpg"
      SOURCE_PROMPT="A cozy living room photo with a plain white pillow on a brown sofa."
      TARGET_PROMPT="${T5_TARGET_PROMPT_OVERRIDE:-A photo of the same plain white pillow on the same brown sofa, with only the center vertical surface panel changed into same-color white corduroy fabric with fine vertical ribs, while preserving the pillow shape, folds, lighting, contour, sofa, background, and all surrounding pillow fabric.}"
      ATTENTION_TARGET_WORDS="corduroy,ribs,pillow,panel"
      CHANGED_TARGET_WORDS="corduroy,ribs,panel"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="material_panel"
      SUPPORT_NEW_TOKENS="corduroy,ribs,material"
      SUPPORT_HOST_TOKENS="white pillow,center panel"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="white pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="corduroy_panel"
      DECAL_COLOR="128,128,128"
      DECAL_BOX="0.390,0.310,0.560,0.700"
      DECAL_SLANT_X="-0.04"
      DECAL_PERSPECTIVE_Y="0.035"
      DECAL_EDGE_FEATHER_RADIUS="1.5"
      DECAL_TOP_FEATHER_FRAC="0.03"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.60"
      DECAL_OPACITY="1.0"
      TASK_DECAL_REF_GUIDANCE_SCALE="${T5_REF_GUIDANCE_SCALE:-0.36}"
      TASK_DECAL_REF_LUMA_PRESERVE="${T5_REF_LUMA_PRESERVE:-0.62}"
      TASK_DECAL_REF_GRADIENT_PRESERVE="${T5_REF_GRADIENT_PRESERVE:-0.24}"
      TASK_OPFIELD_DECAL_HEDIT="${T5_OPFIELD_HEDIT:-0.58}"
      TASK_OPFIELD_DECAL_TEXT="${T5_OPFIELD_TEXT:-0.10}"
      TASK_OPFIELD_DECAL_REC="${T5_OPFIELD_REC:-0.48}"
      TASK_OPFIELD_DECAL_TRAJ="${T5_OPFIELD_TRAJ:-0.30}"
      ;;
    pillow_same_color_cable_knit)
      TASK_NAME="pillow_same_color_cable_knit"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/phase2_candidates/pexels_white_pillow_brown_sofa_6312089.jpg"
      SOURCE_PROMPT="A cozy living room photo with a plain white pillow on a brown sofa."
      TARGET_PROMPT="${T5_TARGET_PROMPT_OVERRIDE:-A photo of the same white pillow on the same brown sofa, with the entire pillow surface changed into same-color white chunky cable-knit fabric with thick braided knitted columns, while preserving the pillow shape, outline, lighting, sofa, background, and the rest of the scene.}"
      ATTENTION_TARGET_WORDS="knit,cable,braided,pillow"
      CHANGED_TARGET_WORDS="knit,cable,braided"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="material_panel"
      SUPPORT_NEW_TOKENS="knit,cable,braided,material"
      SUPPORT_HOST_TOKENS="white pillow,pillow surface"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="white pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="${T5_DECAL_SHAPE:-waffle_panel}"
      DECAL_COLOR="128,128,128"
      DECAL_BOX="${T5_DECAL_BOX:-0.195,0.300,0.558,0.830}"
      DECAL_SLANT_X="${T5_DECAL_SLANT_X:--0.02}"
      DECAL_PERSPECTIVE_Y="${T5_DECAL_PERSPECTIVE_Y:-0.020}"
      DECAL_EDGE_FEATHER_RADIUS="${T5_DECAL_EDGE_FEATHER_RADIUS:-2.0}"
      DECAL_TOP_FEATHER_FRAC="0.02"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.65"
      DECAL_OPACITY="1.0"
      TASK_DECAL_REF_GUIDANCE_SCALE="${T5_REF_GUIDANCE_SCALE:-0.08}"
      TASK_DECAL_REF_LUMA_PRESERVE="${T5_REF_LUMA_PRESERVE:-0.60}"
      TASK_DECAL_REF_GRADIENT_PRESERVE="${T5_REF_GRADIENT_PRESERVE:-0.20}"
      TASK_OPFIELD_DECAL_HEDIT="${T5_OPFIELD_HEDIT:-0.68}"
      TASK_OPFIELD_DECAL_TEXT="${T5_OPFIELD_TEXT:-0.14}"
      TASK_OPFIELD_DECAL_REC="${T5_OPFIELD_REC:-0.40}"
      TASK_OPFIELD_DECAL_TRAJ="${T5_OPFIELD_TRAJ:-0.25}"
      TASK_FINAL_REF_COMPOSITE_SCALE="${T5_FINAL_REF_COMPOSITE_SCALE:-0.0}"
      TASK_FINAL_REF_COMPOSITE_BLUR="${T5_FINAL_REF_COMPOSITE_BLUR:-1.6}"
      TASK_FINAL_CHROMA_SOURCE_SCALE="${T5_FINAL_CHROMA_SOURCE_SCALE:-1.0}"
      TASK_FINAL_CHROMA_SOURCE_BLUR="${T5_FINAL_CHROMA_SOURCE_BLUR:-2.0}"
      TASK_FINAL_OUTSIDE_RESTORE_SCALE="${T5_FINAL_OUTSIDE_RESTORE_SCALE:-1.0}"
      ;;
    pillow_same_color_linen_panel)
      TASK_NAME="pillow_same_color_linen_panel"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_plain_pillow_sofa_phase1.jpg"
      SOURCE_PROMPT="A cozy living room photo with a plain dark grey pillow on a rattan-backed sofa beside a wooden table, soft natural light, and a simple home interior."
      TARGET_PROMPT="A photo of the same plain dark grey pillow on the same rattan-backed sofa, with only the center surface panel changed into same-color dark grey coarse woven linen, while preserving the pillow shape, seams, folds, lighting, sofa, table, wall, and all surrounding pillow fabric."
      ATTENTION_TARGET_WORDS="linen,woven,grey,pillow,panel"
      CHANGED_TARGET_WORDS="linen,woven,panel"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="material_panel"
      SUPPORT_NEW_TOKENS="linen,woven,material"
      SUPPORT_HOST_TOKENS="dark grey pillow,center panel"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="grey pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="linen_panel"
      DECAL_COLOR="128,128,128"
      DECAL_BOX="0.535,0.500,0.685,0.665"
      DECAL_SLANT_X="-0.05"
      DECAL_PERSPECTIVE_Y="0.040"
      DECAL_EDGE_FEATHER_RADIUS="1.8"
      DECAL_TOP_FEATHER_FRAC="0.04"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.65"
      DECAL_OPACITY="1.0"
      TASK_DECAL_REF_GUIDANCE_SCALE="0.42"
      TASK_DECAL_REF_LUMA_PRESERVE="0.60"
      TASK_DECAL_REF_GRADIENT_PRESERVE="0.22"
      TASK_OPFIELD_DECAL_HEDIT="0.62"
      TASK_OPFIELD_DECAL_TEXT="0.16"
      TASK_OPFIELD_DECAL_REC="0.46"
      TASK_OPFIELD_DECAL_TRAJ="0.28"
      ;;
    pillow_same_color_terry_panel)
      TASK_NAME="pillow_same_color_terry_panel"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/phase2_candidates/pexels_green_chair_white_pillow_6312055.jpg"
      SOURCE_PROMPT="A photo of a plain white throw pillow centered on a green velvet armchair against a tiled wall."
      TARGET_PROMPT="A photo of the same plain white throw pillow on the same green velvet armchair, with only the center rectangular surface panel changed into same-color white terry cloth texture, while preserving the pillow shape, seams, shadows, chair, tiled wall, floor, and all surrounding pillow fabric."
      ATTENTION_TARGET_WORDS="terry,cloth,texture,pillow,panel"
      CHANGED_TARGET_WORDS="terry,cloth,panel"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="material_panel"
      SUPPORT_NEW_TOKENS="terry,cloth,material"
      SUPPORT_HOST_TOKENS="white pillow,center panel"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="white pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="terry_panel"
      DECAL_COLOR="128,128,128"
      DECAL_BOX="0.475,0.295,0.625,0.505"
      DECAL_SLANT_X="0.00"
      DECAL_PERSPECTIVE_Y="0.010"
      DECAL_EDGE_FEATHER_RADIUS="1.0"
      DECAL_TOP_FEATHER_FRAC="0.02"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.75"
      DECAL_OPACITY="1.0"
      TASK_DECAL_REF_GUIDANCE_SCALE="0.44"
      TASK_DECAL_REF_LUMA_PRESERVE="0.58"
      TASK_DECAL_REF_GRADIENT_PRESERVE="0.22"
      TASK_OPFIELD_DECAL_HEDIT="0.66"
      TASK_OPFIELD_DECAL_TEXT="0.18"
      TASK_OPFIELD_DECAL_REC="0.44"
      TASK_OPFIELD_DECAL_TRAJ="0.28"
      ;;
    P7|backpack_remove_toy_charm)
      TASK_NAME="backpack_remove_toy_charm"
      TASK_KIND="remove_semantic"
      IMAGE="${ROOT}/data/pretty_free_candidates/unsplash_backpack_keychain_njwnKDUDKNM.jpg"
      SOURCE_PROMPT="A close-up photo of a grey backpack with a yellow dangling toy charm attached to a pink keychain strap."
      TARGET_PROMPT="A close-up photo of the same grey backpack with the yellow dangling toy charm removed, pink strap, zipper, and fabric preserved."
      ATTENTION_TARGET_WORDS="toy,charm,backpack,zipper,fabric"
      CHANGED_TARGET_WORDS="toy,charm"
      SUPPORT_EDIT_OPERATION="remove_object"
      SUPPORT_HOST_TOKENS="backpack"
      SUPPORT_REMOVED_TOKENS="toy,charm"
      SUPPORT_V2_CANDIDATE="removed_src_x_clean"
      SUPPORT_V3_RELATION="remove_source_object"
      SEMANTIC_PHRASE="yellow dangling toy charm"
      SEMANTIC_DILATE="6"
      SEMANTIC_BLUR="1"
      SUPPORT_RELATION="inside"
      ;;
    *)
      echo "Unknown TASK '${task_id}'. Valid Core-6 tasks: cat_crown bowl_apple_inside tshirt_star red_chair_blue pillow_same_color_cable_knit backpack_remove_toy_charm. Additional T5 candidates: pillow_same_color_corduroy_panel pillow_same_color_linen_panel pillow_same_color_terry_panel. Diagnostic legacy T5: pillow_vertical_fabric_strip." >&2
      exit 2
      ;;
  esac
}
