#!/usr/bin/env bash

# Canonical WACV Phase 1 Core-6 task configuration. Historical probes live in
# legacy/cleanup_20260603 or the full legacy runner snapshot.

task_config() {
  local task_id="$1"
  TASK_NAME=""
  TASK_KIND=""
  IMAGE=""
  SOURCE_PROMPT=""
  TARGET_PROMPT=""
  ATTENTION_TARGET_WORDS=""
  CHANGED_TARGET_WORDS=""
  SUPPORT_EDIT_OPERATION="auto"
  SUPPORT_NEW_TOKENS=""
  SUPPORT_HOST_TOKENS=""
  SUPPORT_REMOVED_TOKENS=""
  SUPPORT_LOCAL_TARGET_PROMPT=""
  SUPPORT_V2_CANDIDATE=""
  SUPPORT_V3_CANDIDATE="operation_default"
  SUPPORT_V3_RELATION="auto"
  SEMANTIC_PHRASE=""
  SEMANTIC_DILATE="0"
  SEMANTIC_BLUR="0"
  SUPPORT_RELATION="auto"
  SUPPORT_PRESET=""
  DECAL_SHAPE=""
  DECAL_COLOR=""
  DECAL_BOX=""
  DECAL_SLANT_X="0.0"
  DECAL_PERSPECTIVE_Y="0.0"
  DECAL_EDGE_FEATHER_RADIUS="0.0"
  DECAL_TOP_FEATHER_FRAC="0.0"
  DECAL_TOP_FEATHER_MIN_ALPHA="0.0"
  DECAL_OPACITY=""
  RECOLOR_TARGET_COLOR=""
  RECOLOR_SURFACE_NAME=""
  RECOLOR_BOX=""
  RECOLOR_SOURCE_COLOR=""
  REPLACEMENT_COLOR="blue"
  REPLACEMENT_SHAPE="semantic"
  REPLACEMENT_OPACITY="0.98"
  REPLACEMENT_SCALE="0.78"
  REPLACEMENT_BLUR="0.7"
  REPLACEMENT_BACKGROUND_MODE="patch"
  REPLACEMENT_OUTLINE="0"
  REPLACEMENT_HEDIT_GUIDANCE_SCALE="0.62"
  REPLACEMENT_TEXT_GUIDANCE_SCALE="0.06"
  REPLACEMENT_REF_GUIDANCE_SCALE="0.42"
  REPLACEMENT_REC_GUIDANCE_SCALE="0.20"
  REPLACEMENT_TRAJECTORY_PRESERVE_SCALE="0.14"
  REPLACEMENT_OLD_PHRASE=""
  REPLACEMENT_TARGET_PHRASE=""

  case "${task_id}" in
    P1|cat_crown)
      TASK_NAME="cat_crown"
      TASK_KIND="accessory_semantic"
      IMAGE="${ROOT}/data/paper_images/cat_sitting_in_grass.jpg"
      SOURCE_PROMPT="A photo of a cat sitting in grass."
      TARGET_PROMPT="A photo of the same cat sitting in the same grass, wearing a small golden crown centered on top of its head between the ears."
      ATTENTION_TARGET_WORDS="crown,head"
      CHANGED_TARGET_WORDS="crown"
      SUPPORT_EDIT_OPERATION="add_object"
      SUPPORT_NEW_TOKENS="crown"
      SUPPORT_HOST_TOKENS="cat,head"
      SUPPORT_V2_CANDIDATE="new_plus_host_x_clean"
      SUPPORT_V3_RELATION="above_host"
      SEMANTIC_PHRASE="cat"
      SUPPORT_LOCAL_TARGET_PROMPT="A close-up photo of a small golden crown centered on top of a cat's head between the ears."
      ;;
    bowl_apple_inside)
      TASK_NAME="bowl_apple_inside"
      TASK_KIND="object_in_container"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_empty_ceramic_bowl_phase1.jpg"
      SOURCE_PROMPT="A top-down photo of an empty blue ceramic bowl on a wooden board in a tidy table setting, with no fruit inside the bowl."
      TARGET_PROMPT="A top-down photo of the same blue ceramic bowl on the same wooden board, with one small red apple centered inside the bowl, while the bowl, board, tableware, leaves, and background remain unchanged."
      ATTENTION_TARGET_WORDS="apple,bowl,inside"
      CHANGED_TARGET_WORDS="apple"
      SUPPORT_EDIT_OPERATION="add_object"
      SUPPORT_NEW_TOKENS="apple"
      SUPPORT_HOST_TOKENS="bowl,ceramic bowl"
      SUPPORT_V2_CANDIDATE="new_plus_host_x_clean"
      SUPPORT_V3_RELATION="inside_container"
      SEMANTIC_PHRASE="blue ceramic bowl"
      SUPPORT_RELATION="inside"
      SUPPORT_LOCAL_TARGET_PROMPT="A close-up top-down photo of one small red apple centered inside the empty blue ceramic bowl, fully within the inner basin and away from the rim."
      ;;
    P5|tshirt_star)
      TASK_NAME="tshirt_star"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_person_white_tshirt_blue_jeans_8217483.jpg"
      SOURCE_PROMPT="A close-up fashion photo of a person wearing a plain white t-shirt and blue jeans, with natural fabric folds and soft studio lighting."
      TARGET_PROMPT="The same person wearing the same white t-shirt and blue jeans, with a clearly visible medium-sized bright red star printed on the center chest, while preserving the fabric folds, shadows, jeans, pose, and background."
      ATTENTION_TARGET_WORDS="star,t-shirt,chest"
      CHANGED_TARGET_WORDS="star"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="clothing_decal"
      SUPPORT_NEW_TOKENS="star"
      SUPPORT_HOST_TOKENS="t-shirt,shirt"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="t-shirt"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="star"
      DECAL_COLOR="red"
      DECAL_BOX="0.40,0.30,0.62,0.55"
      ;;
    P4|red_chair_blue|red_chair_to_blue_chair)
      TASK_NAME="red_chair_blue"
      TASK_KIND="recolor_semantic"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_red_armchair_room_6758347.jpg"
      SOURCE_PROMPT="A photo of a red armless rounded upholstered chair in a stylish room."
      TARGET_PROMPT="A photo of the same armless rounded upholstered chair in the same stylish room, with only the fabric color changed to deep blue, no armrests added."
      ATTENTION_TARGET_WORDS="chair,blue"
      CHANGED_TARGET_WORDS="chair"
      SUPPORT_EDIT_OPERATION="recolor"
      SUPPORT_NEW_TOKENS="blue"
      SUPPORT_HOST_TOKENS="chair"
      SUPPORT_REMOVED_TOKENS="chair"
      SUPPORT_V3_RELATION="inside"
      SEMANTIC_PHRASE="chair"
      SUPPORT_RELATION="inside"
      RECOLOR_TARGET_COLOR="blue"
      RECOLOR_SURFACE_NAME="chair"
      ;;
    pillow_vertical_fabric_strip)
      TASK_NAME="pillow_vertical_fabric_strip"
      TASK_KIND="decal"
      IMAGE="${ROOT}/data/pretty_free_candidates/pexels_plain_pillow_sofa_phase1.jpg"
      SOURCE_PROMPT="A cozy living room photo with a plain grey pillow on a sofa, soft natural light, and a simple home interior."
      TARGET_PROMPT="A photo of the same plain grey pillow with one vertical glossy blue silk strip sewn down the center of the pillow surface, tucked naturally into the top pillow seam with soft satin highlights and smooth silk texture, while the pillow shape, sofa, table, wall, and background remain unchanged."
      ATTENTION_TARGET_WORDS="blue,silk,vertical,strip,pillow"
      CHANGED_TARGET_WORDS="blue,silk,strip"
      SUPPORT_EDIT_OPERATION="add_decal"
      SUPPORT_PRESET="surface_strip"
      SUPPORT_NEW_TOKENS="blue,silk,strip"
      SUPPORT_HOST_TOKENS="pillow"
      SUPPORT_V3_RELATION="on_surface"
      SEMANTIC_PHRASE="grey pillow"
      SUPPORT_RELATION="inside"
      DECAL_SHAPE="slanted_rectangle"
      DECAL_COLOR="58,132,215"
      DECAL_BOX="0.565,0.445,0.665,0.688"
      DECAL_SLANT_X="-0.08"
      DECAL_PERSPECTIVE_Y="0.055"
      DECAL_EDGE_FEATHER_RADIUS="7.0"
      DECAL_TOP_FEATHER_FRAC="0.16"
      DECAL_TOP_FEATHER_MIN_ALPHA="0.0"
      DECAL_OPACITY="0.80"
      ;;
    P7|backpack_remove_toy_charm)
      TASK_NAME="backpack_remove_toy_charm"
      TASK_KIND="remove_semantic"
      IMAGE="${ROOT}/data/pretty_free_candidates/unsplash_backpack_keychain_njwnKDUDKNM.jpg"
      SOURCE_PROMPT="A close-up photo of a grey backpack with a yellow dangling toy charm attached to a pink keychain strap."
      TARGET_PROMPT="A close-up photo of the same grey backpack with the yellow dangling toy charm removed, pink strap, zipper, and fabric preserved."
      ATTENTION_TARGET_WORDS="toy,charm,backpack,zipper,fabric"
      CHANGED_TARGET_WORDS="toy,charm"
      SUPPORT_EDIT_OPERATION="remove_object"
      SUPPORT_HOST_TOKENS="backpack"
      SUPPORT_REMOVED_TOKENS="toy,charm"
      SUPPORT_V2_CANDIDATE="removed_src_x_clean"
      SUPPORT_V3_RELATION="remove_source_object"
      SEMANTIC_PHRASE="yellow dangling toy charm"
      SEMANTIC_DILATE="6"
      SEMANTIC_BLUR="1"
      SUPPORT_RELATION="inside"
      ;;
    *)
      echo "Unknown TASK '${task_id}'. Valid Core-6 tasks: cat_crown bowl_apple_inside tshirt_star red_chair_blue pillow_vertical_fabric_strip backpack_remove_toy_charm." >&2
      exit 2
      ;;
  esac
}
