from __future__ import annotations

import importlib.util
from pathlib import Path


TASKS = [
    "cat_crown",
    "dog_bow_tie_phase2",
    "dog_front_sunglasses_phase2",
    "bowl_apple_inside",
    "white_bowl_orange_tabletop_phase2",
    "brown_bowl_lemon_phase2",
    "tshirt_star",
    "mug_heart",
    "tote_leaf",
    "red_office_chair_to_blue_office_chair",
    "green_mug_orange_phase2",
    "yellow_vase_blue_phase2",
]


def load_base_module():
    path = Path(__file__).with_name("summarize_e3_support_geometry.py")
    spec = importlib.util.spec_from_file_location("e3_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    module = load_base_module()
    module.TASKS = TASKS
    module.OUT = module.EXP / "e3_support_geometry_t1_t4"
    result = module.main()
    complete = module.OUT / "e3_support_geometry_t1_t4_complete_2026-06-09.md"
    rows = module.read_csv(module.OUT / "e3_support_geometry_mask_metrics.csv")
    complete_rows = sum(1 for row in rows if row.get("complete") == "1")
    expected = len(TASKS) * len(module.SEEDS) * len(module.VARIANTS)
    complete.write_text(
        "\n".join(
            [
                "# E3 T1-T4 Support Geometry Completion",
                "",
                "Date: 2026-06-09",
                "",
                f"Scope: Phase2 T1-T4, {len(TASKS)} tasks x {len(module.SEEDS)} seeds x {len(module.VARIANTS)} support variants.",
                f"Support rows complete: {complete_rows}/{expected}",
                "",
                "Artifacts:",
                f"- `{module.OUT / 'e3_support_geometry_mask_metrics.csv'}`",
                f"- `{module.OUT / 'e3_support_geometry_summary.csv'}`",
                f"- `{module.OUT / 'e3_support_geometry_by_task_summary.csv'}`",
                f"- `{module.OUT / 'e3_support_geometry_correlation.csv'}`",
                f"- `{module.OUT / 'e3_support_geometry_summary.md'}`",
                "",
                "Note: T1-T4 rerun uses the T1-T4 eval assets generated by `scripts/prepare_t1_t4_eval_assets.py`.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {complete}")
    if complete_rows != expected:
        return 1
    return result


if __name__ == "__main__":
    raise SystemExit(main())
